dictionary g_langs = {
	{"af", "African"},
	{"sq", "Albanian"},
	{"ar", "Arabic"},
	{"hy", "Armenian"},
	{"bn", "Bengali"},
	{"bs", "Bosnian"},
	{"bg", "Bulgarian"},
	{"ct", "Catalan"},
	{"hr", "Croatian"},
	{"cs", "Czech"},
	{"da", "Danish"},
	{"nl", "Dutch"},
	{"au", "English (Austrailia)"},
	{"ca", "English (Canada)"},
	{"in", "English (India)"},
	{"ir", "English (Ireland)"},
	{"afs", "English (South Africa)"},
	{"ek", "English (United Kingdom)"},
	{"en", "English (United States)"},
	{"eo", "Esperanto"},
	{"et", "Estonian"},
	{"tl", "Filipino"},
	{"fi", "Finnish"},
	{"fc", "French (Canada)"},
	{"fr", "French (France)"},
	{"de", "German"},
	{"el", "Greek"},
	{"hi", "Hindi"},
	{"hu", "Hungarian"},
	{"is", "Icelandic"},
	{"id", "Indonesian"},
	{"it", "Italian"},
	{"ja", "Japanese"},
	{"jw", "Javanese"},
	{"kn", "Kannada"},
	{"km", "Khmer"},
	{"ko", "Korean"},
	{"la", "Latin"},
	{"lv", "Latvian"},
	{"mk", "Macedonian"},
	{"cn", "Mandarin (China Mainland)"},
	{"tw", "Mandarin (Taiwan)"},
	//{"my","Myanmar (Burmese)"},
	{"ne", "Nepali"},
	{"no", "Norwegian"},
	{"pl", "Polish"},
	{"br", "Portuguese (Brazil)"},
	{"pt", "Portuguese (Portugal)"},
	{"ro", "Romanian"},
	{"ru", "Russian"},
	{"mx", "Spanish (Mexico)"},
	{"es", "Spanish (Spain)"},
	{"ma", "Spanish (United States)"},
	{"sr", "Serbian"},
	{"si", "Sinhala"},
	{"sk", "Slovak"},
	{"su", "Sundanese"},
	{"sw", "Swahili"},
	{"sv", "Swedish"},
	{"ta", "Tamil"},
	{"te", "Telugu"},
	{"th", "Thai"},
	{"tr", "Turkish"},
	{"uk", "Ukrainian"},
	{"ur", "Urdu"},
	{"vi", "Vietnamese"},
	{"cy", "Welsh"}
};
